services:
  go_plugin_compile:
    build:
      context: simple
      dockerfile: ../../shared/golang/Dockerfile
      target: golang-base
    command: >
      bash -c "
      cd examples/jaeger-tracing/simple
      && go build -o /output/simple.so -buildmode=c-shared ."
    working_dir: /source
    environment:
      - GOFLAGS=-buildvcs=false
    volumes:
      - ../..:/source
      - ./lib:/output
